services:
  - type: web
    name: tg-tag
    runtime: docker
    branch: main
    dockerfilePath: ./Dockerfile
    dockerContext: .
    plan: starter
    maxShutdownDelaySeconds: 60
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: ADMIN_ID
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: REPLICATE_API_TOKEN
        sync: false
      - key: STABILITY_API_KEY
        sync: false
      - key: OPENWEATHER_API_KEY
        sync: false
      - key: SCREENSHOT_API_KEY
        sync: false
      - key: TMDB_API_KEY
        sync: false
      - key: GMAIL_ADDRESS
        sync: false
      - key: GMAIL_APP_PASSWORD
        sync: false
      - key: YTDL_COOKIES_FILE
        value: /etc/secrets/cookies_youtube.txt
